### PR TITLE
Plamen dev

### PR DESCRIPTION
**Pull request by rabadzhiyski**
set up locally poetry

### CODE REVIEW

**Comment by rabadzhiyski** [comment]
I had some troubles mainly due to the poetry installation on my Linux machine. After some trial and error, I managed to pass it. However, I'd need help from someone to test on Windows and MacOS. Thanks,

**Comment by mdancho84** [comment]
Thanks for doing this plamen

**Comment by saad077** [comment]
I will test it on windows and update it here shortly. Thanks

> I had some troubles mainly due to the poetry installation on my Linux machine. After some trial and error, I managed to pass it. However, I'd need help from someone to test on Windows and MacOS. Thanks,

**Comment by saad077** [comment]
I installed all the packages using poetry on windows. It successfully installed all packages. I had a failure in installation as I had python 3.12 even though I changed the condition in pyproject.toml file but gave an error but once I reduced the version of python to 3.11, it works

**Comment by mdancho84** [comment]
I will in the future set up GitHub actions. We did this for pytimetk and we've identified a lot of issues with polars and pandas along with testing on various platforms.

**Pull request merged**
